name: publish

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@v2
        with:
          version: 10

      - run: pnpm install --frozen-lockfile

      - name: Fetch NFT metadata
        run: pnpm run get-metadata
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          VITE_CONTRACT_ADDRESS: ${{ secrets.VITE_CONTRACT_ADDRESS }}

      - name: Extract ASCII art from contract
        run: pnpm run extract-ascii
        env:
          VITE_CONTRACT_ADDRESS: ${{ secrets.VITE_CONTRACT_ADDRESS }}
          VITE_CHAIN: ${{ secrets.VITE_CHAIN }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

      - name: Build application
        run: pnpm run build
        env:
          VITE_CONTRACT_ADDRESS: ${{ secrets.VITE_CONTRACT_ADDRESS }}
          VITE_CHAIN: ${{ secrets.VITE_CHAIN }}

      - name: Deploy to Arweave
        run: |
          echo "Checking DEPLOY_KEY length: ${#DEPLOY_KEY}"
          echo "ARNS_NAME: $ARNS_NAME"
          if [ -n "$UNDER_NAME" ]; then
            echo "Deploying with undername: $UNDER_NAME"
            npx permaweb-deploy --arns-name $ARNS_NAME --undername $UNDER_NAME --deploy-key "$DEPLOY_KEY"
          else
            echo "Deploying without undername..."
            npx permaweb-deploy --arns-name $ARNS_NAME --deploy-key "$DEPLOY_KEY"
          fi
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          ARNS_NAME: ${{ secrets.ARNS_NAME }}
          UNDER_NAME: ${{ secrets.UNDER_NAME }}
